---
sudo: required
env:
  - >
    container_id=$(mktemp)
    distribution=centos
    version=7
    init=/usr/lib/systemd/systemd
    run_opts="--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  - sudo apt-get update
  # Pull container
  - sudo docker pull ${distribution}:${version}
  # Customize container
  - sudo docker build --rm=true --file=tests/Dockerfile.${distribution} --tag=${distribution}:ansible tests
  #Install libxml2-utils
  #- sudo docker exec "$(cat ${container_id})" sudo yum install libxml2-utils


script:
    # Run container in detached state
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/shibboleth:ro ${run_opts} ${distribution}:ansible "${init}" > "${container_id}"

    # Syntax check
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/shibboleth/tests/test.yml --syntax-check
    # Test role
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/shibboleth/tests/test.yml -vvv
    # Idempotence test
  - >
    sudo docker exec "$(cat ${container_id})" ansible-playbook -vv /etc/ansible/roles/shibboleth/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

    # Show the xmlfile i terminal
  - sudo docker exec "$(cat ${container_id})" cat /etc/shibboleth/shibboleth2.xml

    # Show extensions.xml file
  - sudo docker exec "$(cat ${container_id})" cat /etc/shibboleth/extensions.xml

    # Try to generate metadata file
  - sudo docker exec "$(cat ${container_id})" /etc/shibboleth/metagen.sh -c /etc/shibboleth/sp-cert.pem -h MYservreCname.se

    # cat file /etc/shibboleth/metadata_pre.xml
  - sudo docker exec "$(cat ${container_id})" cat /etc/shibboleth/metadata.xml

    # Clean up
  - sudo docker stop "$(cat ${container_id})"

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
