---
# handlers file for shibboleth
- name: restart httpd 
  service:
    name: httpd.service
    state: restarted
    enabled: yes

- name: restart shibd 
  service:
    name: shibd.service
    state: restarted
    enabled: yes

- name: merge metadata
  blockinfile:
    block: "{{ lookup('file', '/etc/shibboleth/extensions.xml') }}"
    dest: "/etc/shibboleth/metadata_pre.xml"
    insertafter: "<md:SPSSODescriptor"
